import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";


import LayoutHeader from "@/shared/layout/header/LayoutHeader";
import LayoutFooter from "@/shared/layout/footer/LayoutFooter";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col justify-between gap-5">
        <LayoutHeader self-start/>
        {children}
        <LayoutFooter />
      </body>
    </html>
  );
}
