export type Property= {
    id: number,
    code: number,
    city: string,
    zone: string,
    city_zone: string,
    neighborhood: string,
    type: string,
    biz: string,
    area_cons:number,
    area_lot:number,
    bedrooms:number,
    bathrooms:number,
    parking: number,
    price_format:string,
    administration: number,
    latitude:string,
    longitude:string,
    description:string,
    image: string,
}