export type domusQuery = {
    page?: number,
    city?: string,
    neighborhood_code?: string,
    type?: string,  
    biz?: string,
    bedrooms?: string,
    minbed?: string,
    maxbed?: string,
    bathrooms?: string,
    minbath?: string,
    maxbath?: string,
    pvmin?:number,
    pvmax?:number,
    pcmin?:number,
    pcmax?:number,
    minarea?: number,
    maxarea?: number,
    stratum?: string,
    destination?: number,
    great?: "on";
}